### PR TITLE
Small Improvements

### PR DESCRIPTION
**Pull request by eljamm**
Hey @alexthillen,

First and foremost, I just want to thank you for picking up the maintenance for the addon and for the amazing job you've done so far! It's been the best solution I found to highlight code and version control my Anki collection with [ki](https://github.com/langfield/ki) while also writing everything in markdown.

That being said, I've spent a bit of time making it easier to use and maintain, so I hope this is useful. Here is a quick summary:

- **Dynamic CSS:** Currently any modification to the note style resets each time Anki restarts. This change makes the note types load "style.css" from the media folder, making it possible for users to overwrite it.
- **Reusing HTML:** The HTML templates share a lot of common code. Extracting them into a common dependency makes their maintenance easier and clearer.
- **Remove deprecated code:** The deprecated code is almost 3 years old at this point. I don't know if it's good to keep it around as it will break the addon with future updates.

Please let me know if you think anything should be changed or if there are further improvements.

### CODE REVIEW

**Comment by alexthillen** [comment]
Hi @eljamm 

This looks really great, thanks a lot! I will try to have another look in the upcoming days, then we can merge 🕺

**Comment by alexthillen** [comment]
We can merge it like this, if you like. There is just one small thing I'm wondering about.

In the case where the user already has some `style.css` that is very old (as was the case when I just tested it :D ), while he actually just liked the styling we were providing before. Then from now on, his old styling might be used while he is not even aware of why ...
Maybe we can migrate to `style_mdkatex.css` allowing this feature for customizations from now on, stating with our current styling? Alternatively, maybe we could do something like this :
`css = <our styling that is updated> + "@import url(user_styles.css);` where the user's styles should have precedence, but we still could add some improvements in the future if needed? What do you think? 

Thanks again for the great contribution. 😀

**Comment by eljamm** [comment]
I like your idea of separating the user and the addon styles. This way, the user can keep up to date with the addon style changes and just override the values he wants :smile:

I actually found two ways to do this, both of them coming from a simple issue:
In Anki, we can either have the user and addon styles be dynamically imported or generated into the style, but not both at the same time. Example:

```python
# HTMLandCSS.py
css = read_file("css/style.css")                                    # Works
css = read_file("css/style.css") + "\n@import url(user_style.css);" # Does not work
css = "@import url(style.css);\n" + "@import url(user_style.css);"  # Works
```

## Import Styles
This solution is easier to implement, we have:
```python
# HTMLandCSS.py
css = "@import url(style.css);\n" + "@import url(user_style.css);"
```
When Anki starts, the addon copies `style.css` to the media folder. The user can then create `user_style.css` and modify it as he wants. Let's say a user wants to implement his own night mode colors and put fields in a centered block:
```css
/* user_style.css */
.nightMode, .night-mode, .night_mode {
  background-color: #1e1e2e !important; 
  color: #cdd6f4 !important;
}

.nightMode code {
  filter: unset !important;
}

/* field not set in style.css,
so !important is not necessary here */
.field {
  display: inline-block;
  text-align: left;
}
```
If something was previously defined, it's important to set `!important` (pun intended 😁). If it's something new (like `field` in the above example), then there is no need.

## Generate Styles
This solution is a little bit more involved. In `HTMLandCSS.py`, the default style is loaded normally, but then in `__init__.py`, we check if the `user_style.css` exists in the media folder and we concatenate it with the css definition if it does:
```python
# HTMLandCSS.py
css = read_file("css/style.css")
```
```python
# What should we name this?
def get_user_style():
    style_path = os.path.join(mw.col.media.dir(), "user_style.css")
    if os.path.isfile(style_path):
        return  "\n" + file_to_string(style_path)
    return ""

# Example
def create_model():
    """Creates the Basic Card type"""
    # ...
    template = m.newTemplate(MODEL_NAME + " Basic (Color)")
    template["qfmt"] = front
    template["afmt"] = back
    model["css"] = css + get_user_style()
    #  ...
```
This leads to the following style inside the card type:
```css
/* Default */
.card, .fields {
  font-family: arial;
  font-size: 20px;
  color: black;
  background-color: white;
}
/* etc... */

/* User-defined */
.nightMode, .night-mode, .night_mode {
  background-color: #1e1e2e !important; 
  color: #cdd6f4 !important;
}
/* etc... */
```

I'll commit both changes and you can try them out and see which one you like more. By the way, the markdown preview can also be overriden by the user style now 😁

Also, sorry for the lengthy reply 😅

**Comment by alexthillen** [comment]
Woow, you are blazingly fast! And nice job! 😄 I like both methods. The second one should be ready to go. I will try to test it tomorrow. For the first one, I have two thoughts:
1. The behavior now is that `style.css` is only added to Anki media if it doesn't exist until now (which we probably). So, we need to overwrite this behavior and always overwrite, with the latest styles, while keeping `user_styles.css` untouched.
2. I'm wondering what will happen on Anki mobile, as I imagine `style.css` will not be available there (?), or we need to pass a link to css. However, if the styles are baked right into the note type styling, then it should definitely be available.

What do you think?

**Comment by eljamm** [comment]
Thanks, I really enjoy tinkering in my free time 😁, but I should thank you too for your fast feedback and great suggestions 🚀

For mobile, I can only test on AnkiDroid and both methods work fine there. As for overwriting the `style.css` file, I tested it with the following and it worked without any problem:
```diff
-    _add_file(os.path.join(addon_path, "css",  "style.css"), "style.css")
+    _write_data("style_test.css", bytes(read_file("css/style.css"), 'utf-8'))
     _add_file(os.path.join(addon_path, "_katex.min.js"), "_katex.min.js")
```
With:
```python
def _write_data(filename, data):
    mw.col.media.trash_files([filename])
    mw.col.media.write_data(filename, data)
```

That being said, I'm leaning more towards the second method now because users probably want to see the current style inside their card types and having two imports doesn't really tell you much (especially for mobile users).

I'll clean up the code and commit history a bit after you finish testing and then maybe we can have one final look before merging 

Also, we probably should add a little bit of documentation after this as users should know:
1. That editing styles should be done from `user_style.css` and not the note type
2. How to overwrite and unset existing style values
3. That the app needs to be reopened for their changes to take effect

**Comment by alexthillen** [comment]
You are absolutely right! Of course, collection.media is sync'ed. Not sure what I was (late-night) thinking there.. 😁  `_write_data` should take care of the second. Then we are settled!

I actually like that solution of importing the styles. I think it prevents the users from changing styles note types just to find them replaced after re-opening. Editing css within Anki Note Type interface is a mess anyways 😅.

I think seeing something like this should be fairly intuitive. 

```css
/* To customize styles for this note type, please edit the file 'user_style.css', inside your collection media folder,
please refer to: https://docs.ankiweb.net/files.html to find it. */
@import url(style.css);
@import url(user_style.css);
```

In that case, maybe we would want to initialize `user_style.css` with a commented-out placeholder as you pointed out above : 

```css
/* user_style.css */

/* replace with your own styles and make sure to mark properties that should be overwritten as !important

// overwrite
.nightMode, .night-mode, .night_mode {
  background-color: #1e1e2e !important; 
  color: #cdd6f4 !important;
}
.nightMode code {
  filter: unset !important;
}

// field not set in style.css - no need to overwrite (i.e. !important is not necessary here)
.field {
  display: inline-block;
  text-align: left;
}
*/
```

But this is only a slight preference. Do whatever you think is more suited and let me know when it's ready, then I will merge.
For the documentation, you can add it or I can add it - as you like. I will then update [ankiweb addon](https://ankiweb.net/shared/info/1786114227) accordingly. Will mention your great work as well if you don't mind. 🙏

**Comment by eljamm** [comment]
I've cleaned everything up and I really like the results 😃

Since the styles are imported, this means that users don't have to re-open Anki for them to take effect. The addon style is now written after every restart and the user style is only added if it's not there.

I think the comment in the card type and the user style template are clear enough to help users change the style. I also added some documentation for this in the README which you can add or reference in the addon page.

You can check if everything is okay and if you'd like to change anything then please go ahead, else I think we're ready to merge 🥳

**Comment by alexthillen** [comment]
It's amazing! Thanks again!

**Pull request merged**
